version: '3.8'
services:
  my_video_db:
    container_name: my_video_db
    environment:
      - POSTGRES_USER=my_video
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=my_video
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
