environment:
  DATABASE_URL: ${DATABASE_URL}
  DATABASE_USERNAME: ${DATABASE_USERNAME}
  DATABASE_PASSWORD: ${DATABASE_PASSWORD}
  DATABASE_NAME: ${DATABASE_NAME}
  DATABASE_SCHEMA: ${DATABASE_SCHEMA}
  JWT_KEY: ${JWT_KEY}
  DATABASE_PORT: ${DATABASE_PORT}
packages:
- name: authentication
  functions:
  - name: authenticate
    runtime: go:1.20
    web: true
